### ISSUE TITLE
[Bug] Dynamic Timeline blocks missing spaces in text content

### ISSUE THREAD

**Issue by ANYroots** [banisterious/obsidian-canvas-roots#35]
## Environment

- **Plugin version**: 17.2
- **Obsidian version**: 1.10.6
- **Operating system**: Windows 10
- **Installer**: BRAT

## Steps to Reproduce

1. Create or update a person note.
2. Open the person note.
3. View dynamic timeline block content.

## Expected Behavior

Text content in the dynamic timeline block appears with proper spacing and punctuation.

## Actual Behavior

Text content in the dynamic timeline block is missing spaces  - “Bornin” , “Diedin”, “Residedin”

## Screenshots

<img width="846" height="177" alt="Image" src="https://github.com/user-attachments/assets/747aa3f4-b94e-4699-86be-77bc7522d20d" />

**Comment by banisterious** [comment]
Fixed in next release. The issue was that leading whitespace in the place `<span>` element ( `in ${place}`) was being collapsed by HTML rendering. The fix adds an explicit text node with a space before creating the place span, so it now properly displays "Born in" instead of "Bornin".

**Comment by ANYroots** [comment]
Hello, I know this is a minor issue and am not very concerned, but did want to let you know that the the dynamic timeline blocks are still missing spaces.
